### PR TITLE
[READY] Implement AX12 reading support

### PR DESCRIPTION
**Pull request by bstaletic**
AX12 motors respond to every command if everything was okay with the
command sent to them.

Marked as WIP as there is still some functionality not supported by the driver, so let's pick and choose what we want to support.

Not yet covered functionality include:

- [ ]  Read AX12 speed
- [ ]  Read AX12 temperature
- [ ]  Read AX12 load
- [ ]  Read AX12 voltage
- [x]  Read AX12 moving status
- [ ]  Read AX12 position
- [ ] Read AX12 RW status (I have no idea what this actually means, so don't ask)
- [ ] Unstuck

What do you think is necessary and what is nice-to-have functionality?

### CODE REVIEW

**Comment by darko31** [comment]
Moving status and unstuck might be useful. Everything else we could implement later if we need it and have enough time. I also have no idea wtf is RW status.

**Comment by bstaletic** [comment]
I'll implement moving status right away.

As for unstuck, as far as I can tell it's a myth. I can't find it anywhere in [AX12 manual](http://support.robotis.com/en/techsupport_eng.htm#product/dynamixel/ax_series/dxl_ax_actuator.html).

**Comment by bstaletic** [comment]
I've pushed a commit that implements reading moving status and reading the motor response.

The actual [datasheet](http://www.crustcrawler.com/products/bioloid/docs/AX-12.pdf) doesn't seem to mention AX12 unstuck behavior. Does anyone have an idea if such a thing actually exists?

**Comment by darko31** [comment]
Gotta check datasheets and forums first.

**Pull request merged**
